import json
import aiohttp
import re
from dataclasses import dataclass
from typing import Optional
from io import BytesIO
from PIL import (
    Image,
    ImageDraw
)

from datetime import (
    datetime,
    timezone
)

# bot files
from tools.typing import (
    GamePlaylist,
    GameRegion,
    GameInProgress
)

from tools.api_client import (
    PublicAPI,
    PlayFabAPI,
    PlayFabClient
)

# ---------------------------------- basic game info function
async def fetch_game_version(playfab_connection: PlayFabClient) -> Optional[str]:
    """
    returns the formatted game version: v + MajorGameVersion.MinorGameVersion.ClientVersion
    """
    data = await playfab_connection.call_client_api(PlayFabAPI.GET_GAME_VERSION, { "Keys": ["GameInfo"] })
    if not data:
        return None
    game_version = json.loads(data["data"]["Data"]["GameInfo"])["GameVersion"]
    return game_version

async def fetch_build_date(url: str) -> Optional[datetime]:
    """
    Returns the last modified date for the requested build file
    """
    async with aiohttp.ClientSession() as session:
        async with session.head(url, headers={ "User-Agent": "Mozilla/5.0" }) as resp:
            last_mod = resp.headers.get("Last-Modified")
            if last_mod:
                return datetime.strptime(last_mod, "%a, %d %b %Y %H:%M:%S %Z")
    return None

# ---------------------------------- game ccu and server status
async def fetch_regions_list() -> list[str]:
    """
    returns a list of available region **names** (nothing else)
    """
    async with aiohttp.ClientSession() as session:
        async with session.get(PublicAPI.REGIONS) as resp_servers:
            data: dict = await resp_servers.json()
            servers = data.get("regionList", [])

    regions: list[str] = [region["region"] for region in servers]
    return regions

async def fetch_server_stats() -> Optional[tuple[datetime, list[GameRegion], GameRegion]]:
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(PublicAPI.CCU) as resp_ccu:
                ccu: dict = await resp_ccu.json()
    except Exception:
        return None

    updated_at = datetime.fromisoformat(ccu.get("timestamp")) if ccu.get("timestamp") else datetime.now(timezone.utc)
    global_stats = GameRegion(
        name="GLOBAL",
        players={playlist: dict(ccu.get("global", {})).get(playlist.code, 0) for playlist in GamePlaylist}
    )
    region_stats = [
        GameRegion(
            name=region_name,
            players={playlist: dict(region_data).get(playlist.code, 0) for playlist in GamePlaylist}
        )
        for region_name, region_data in dict(ccu.get("perRegion", {})).items()
    ]

    return (updated_at, region_stats, global_stats)

async def fetch_games_list(region: str) -> Optional[dict[GamePlaylist, list[GameInProgress]]]:
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(PublicAPI.GET_GAME_LIST.format(region=region)) as resp:
                data: dict = await resp.json()
                game_list: dict = data.get("serverList", {})
    except Exception:
        return None

    result: dict[GamePlaylist, list[GameInProgress]] = {}
    for game in game_list:
        playlist = GamePlaylist.from_code(game["playlist"])
        result.setdefault(playlist, []).append(GameInProgress(
            name=game["gameId"],
            map=game["gameMap"],
            mode=game["gameMode"],
            players=game["playerCount"],
            max_players=game["maxPlayers"],
            port=int(game["webPort"])
        ))

    return result or None

# ---------------------------------- Player Analysis
PLAYER_XP_LEVELS = [ # AUTOGENERATED FROM XpManager – DO NOT HAND EDIT
    1000,   1757,   3982,   7601,   12544,  18738,  26111,  34591,  44107,  54587,
    65957,  78148,  91086,  104699, 118917, 133666, 148875, 164471, 180384, 196541,
    212870, 229299, 245756, 262170, 278467, 294578, 310428, 325947, 341063, 355703,
    369796, 383269, 396052, 408071, 419255, 429532, 438830, 447077, 454201, 460130,
    464793, 468214, 471127, 473721, 476027, 478072, 479886, 481497, 482935, 484228,
    485405, 486496, 487528, 488532, 489535, 490567, 491656, 492833, 494124, 495560,
    497170, 498981, 501024, 503327, 505918, 508828, 512084, 515716, 519752, 524222,
    529154, 534577, 540520, 547013, 554083, 561761, 570074, 579052, 588723, 599117,
    610262, 622188, 634923, 648496, 662936, 678272, 694533, 711747, 729944, 749153,
    769402, 790721, 813138, 836682, 861382, 887267, 914366, 942708, 972322, 1000000
]

WEAPON_PARSING_TABLE = {
    "crifle": "Combat Rifle",
    "arifle": "Assault Rifle",
    "brifle": "Burst Rifle",
    "pBlaster": "Plasma Blaster",
    "pRocket": "Pocket Rocket",
    "mechProj": "Mech",
    "dBarrel": "Double Barrel"
}

@dataclass
class ModEntry:
    moderator: str = None
    created_at: datetime = None
    title: str = None
    content: str = None

class PlayerProfile:
    def __init__(self):
        # Account information
        self.display_name: str = None
        self.username: str = None
        self.playfab_id: str = None
        self.is_admin: bool = False
        self.created: datetime = None
        self._clan: str = None
        self.mod_history: list[ModEntry] = []
        # Avatar
        self.primary_color: str | None = None
        self.secondary_color: str | None = None
        self.color_theme: tuple[BytesIO, str] | None = None
        self._avatar_mods: list[str] = []
        # Player statistics
        self.level: int = 0
        self.xp: int = 0
        self.matches: int = 0
        self.wins: int = 0
        self.kills: int = 0
        self.deaths: int = 0
        self.flags: int = 0
        self.skulls: int = 0
        self.winstreak: int = 0
        self._best_weapons: dict[str, int] = {}
        # kills statistics
        self.vehicle_kills: int = 0
        self.headshot: int = 0
        self.double_kill: int = 0
        self.triple_kill: int = 0
        self.quad_kill: int = 0
        self.mega_kill: int = 0
        self.ultra_kill: int = 0
        self.monster_kill: int = 0
        self.killing_spree: int = 0
        self.dominating: int = 0
        self.unstoppable: int = 0
        self.godlike: int = 0
        self.assist: int = 0

    @property
    def name(self) -> str:
        return self.display_name if self.display_name.lower() != "none" else self.username if self.username else "*Unknown*"

    @property
    def kd_ratio(self) -> float:
        if not self.kills or not self.deaths:
            return 0.0
        return round(self.kills / max(1, self.deaths), 2)

    @property
    def win_ratio(self) -> str:
        return f"{self.wins / max(1, self.matches) * 100:.1f}%"

    @property
    def clan(self) -> Optional[str]:
        if not self._clan:
            return None
        match = re.search(r"<color=#[0-9a-fA-F]{6}>\[\s*(.*?)\s*\]<\/color>", self._clan)
        return match.group(1) if match else None

    def xp_progress(self, width: int = 20) -> str:
        if self.level >= len(PLAYER_XP_LEVELS):
            return f"{self.xp} XP"

        xp_for_next_level = PLAYER_XP_LEVELS[self.level]
        progress_ratio = min(self.xp / xp_for_next_level, 1.0)
        filled_length = int(progress_ratio * width)
        bar = "█" * filled_length + "░" * (width - filled_length)

        return f"|{bar}| {self.xp:,}/{xp_for_next_level:,} XP"

    @property
    def best_weapons(self) -> Optional[str]:
        weapons_text: list[str] = []
        for weapon, count in self._best_weapons.items():
            if len(weapon) == 3:
                weapon = weapon.upper()
            elif weapon in WEAPON_PARSING_TABLE:
                weapon = WEAPON_PARSING_TABLE.get(weapon)
            weapons_text.append(f"> **{weapon.replace('_', ' ').title()}**: {count:,}")
        return '\n'.join(weapons_text) if weapons_text else None

    @property
    def avatar_mods(self) -> Optional[str]:
        mods_text: list[str] = []
        for mod in self._avatar_mods:
            mod = mod.strip()
            if not mod:
                continue
            if mod != "none" and mod != "unknown":
                mods_text.append(f"> - **{mod.removeprefix("mod_").replace('_', ' ').title()}**") 
        return '\n'.join(mods_text) if mods_text else None

async def fetch_player(playfab_connection: PlayFabClient, name: str) -> Optional[PlayerProfile]:
    # https://learn.microsoft.com/en-us/rest/api/playfab/client/account-management/get-account-info?view=playfab-rest
    player = PlayerProfile()
    profile = await playfab_connection.call_client_api(PlayFabAPI.SEARCH_PLAYER, {"TitleDisplayName": name})
    if not profile:
        profile = await playfab_connection.call_client_api(PlayFabAPI.SEARCH_PLAYER, {"Username": ''.join(char for char in name if char.isalnum())})
        if not profile:
            return None
        player.username = name

    player.created = datetime.fromisoformat(profile["data"]["AccountInfo"]["Created"])
    target_player_id: str = profile["data"]["AccountInfo"]["PlayFabId"]

    player_data = await playfab_connection.call_client_api(PlayFabAPI.GET_PLAYER_DATA, {
        "FunctionName": "getRemoteUserProfile",
        "FunctionParameter": { "remoteId": target_player_id }
    })

    result = dict(player_data["data"]["FunctionResult"])
    player.display_name = str(result.get("DisplayName"))
    player.playfab_id = target_player_id

    mod_notes = list(json.loads(result.get("UserReadOnlyData", {}).get("mod_notes", {}).get("Value", "[]")))
    if mod_notes:
        moderators_cache: dict[str, str | None] = {}
        for entry in mod_notes:
            try:
                assert isinstance(entry, dict)
                _timestamp = int(entry.get("ts", 0))
                _moderator_id = str(entry.get("by") or '')
                _message = str(entry.get("msg") or '')

                if _moderator_id not in moderators_cache.keys():
                    moderator_name = None
                    if _moderator_id:
                        get_mod_name = await playfab_connection.call_client_api(PlayFabAPI.SEARCH_PLAYER, {"PlayFabId": _moderator_id})
                        if not get_mod_name:
                            moderator_name = None
                        mod_account_info = dict(get_mod_name.get("data", {})).get("AccountInfo")
                        if mod_account_info:
                            moderator_name = mod_account_info.get("Username")
                            if not moderator_name:
                                moderator_name = mod_account_info.get("TitleInfo", {}).get("DisplayName")
                    moderators_cache[_moderator_id] = moderator_name
                else:
                    moderator_name = moderators_cache[_moderator_id]

                _message = str(entry.get("msg"))
                if ':' in _message:
                    _message = _message.split(':', 1)
                    title = _message[0].strip() or None
                    content = _message[1].strip() or None
                else:
                    title, content = None, _message

                player.mod_history.append(ModEntry(
                    moderator=moderator_name,
                    title=title,
                    content=content,
                    created_at=(datetime.fromtimestamp(_timestamp/1000) if _timestamp else None)
                ))
            except Exception:
                pass

    properties = dict(json.loads(result.get("UserReadOnlyData", {}).get("Properties", {}).get("Value", {})))
    if properties:
        player.level = properties.get("Level", 0)
        player.xp = properties.get("Experience", 0)
        player.is_admin = bool(properties.get("isAdmin", False))
        player._clan = properties.get("verificationProperties", None)

        achievements = {item["Id"]: item["count"] for item in properties.get("achievementProgressions", [])}
        if achievements:
            player.kills = achievements.get("kills", 0)
            player.deaths = achievements.get("deaths", 0)
            player.matches = achievements.get("games", 0)
            player.wins = achievements.get("wins", 0)
            player.flags  = achievements.get("flags", 0)
            player.skulls = achievements.get("skulls", 0)
            player.winstreak = achievements.get("winstreak", 0)
            player.vehicle_kills = achievements.get("vehKills", 0)
            player.headshot = achievements.get("headshot", 0)
            player.double_kill = achievements.get("kchain_x2", 0)
            player.triple_kill = achievements.get("kchain_x3", 0)
            player.quad_kill = achievements.get("kchain_x4", 0)
            player.mega_kill = achievements.get("kchain_x5", 0)
            player.ultra_kill = achievements.get("kchain_x6", 0)
            player.monster_kill = achievements.get("kchain_x7", 0)
            player.killing_spree = achievements.get("killStreak_x4", 0)
            player.dominating = achievements.get("killStreak_x6", 0)
            player.unstoppable = achievements.get("killStreak_x8", 0)
            player.godlike = achievements.get("killStreak_x10", 0)
            player.assist = achievements.get("assist", 0)

        kill_stats = {str(stat["Id"]).lower(): stat["count"] for stat in properties.get("killStats", [])}
        player._best_weapons = dict(sorted(kill_stats.items(), key=lambda item: item[1], reverse=True)[:5])

    avatar = dict(json.loads(result.get("UserData", {}).get("Loadout", {}).get("Value", "{}")))
    if avatar:
        player._avatar_mods = [str(mod) for mod in avatar.get("avatarMods", [])]
        if avatar.get("color_pri", None):
            player.primary_color = f"#{avatar["color_pri"]}"
        if avatar.get("color_sec", None):
            player.secondary_color = f"#{avatar["color_sec"]}"

        if player.primary_color and player.secondary_color:
            buffer = BytesIO()
            image = Image.new("RGB", (60, 60), color=player.secondary_color)
            draw = ImageDraw.Draw(image)
            draw.polygon(((0, 0), (0, 60), (60, 0)), fill=player.primary_color)
            image.save(buffer, format='PNG')
            buffer.seek(0)
            player.color_theme = (buffer, f"{player.primary_color}|{player.secondary_color}.png")

    return player